# Generated by Django 5.2.6 on 2025-12-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
